"""Library for getting historical and forecasted usage/cost from dominion energy SC API."""

from .dominionsc import DominionSC, DominionSCTFAHandler
from .exceptions import ApiException, CannotConnect, InvalidAuth, MfaChallenge
from .helpers import create_cookie_jar
from .models.forecast import Forecast
from .models.rate_plan import (
    Adjustment,
    Charge,
    Commodity,
    DailyCharge,
    DemandCharge,
    EligibilityRule,
    FlatUsageCharge,
    MonthlyCharge,
    RatePlan,
    Season,
    TieredUsageCharge,
    TimeOfUseCharge,
    TimeOfUsePeriod,
    TimeWindow,
    UsageTier,
    UsageUnit,
)
from .models.usage_read import UsageRead
from .rates import (
    RATE_2,
    RATE_5,
    RATE_6,
    RATE_7,
    RATE_8,
    RATE_32S,
    RATE_32V,
    RESIDENTIAL_ELECTRIC_RATE_PLANS,
    RESIDENTIAL_GAS_RATE_PLANS,
    RESIDENTIAL_RATE_PLANS,
    get_available_rate_plans,
    get_rate_plan,
)

__all__ = [
    "RATE_2",
    "RATE_5",
    "RATE_6",
    "RATE_7",
    "RATE_8",
    "RATE_32S",
    "RATE_32V",
    "RESIDENTIAL_ELECTRIC_RATE_PLANS",
    "RESIDENTIAL_GAS_RATE_PLANS",
    "RESIDENTIAL_RATE_PLANS",
    "Adjustment",
    "ApiException",
    "CannotConnect",
    "Charge",
    "Commodity",
    "DailyCharge",
    "DemandCharge",
    "DominionSC",
    "DominionSCTFAHandler",
    "EligibilityRule",
    "FlatUsageCharge",
    "Forecast",
    "InvalidAuth",
    "MfaChallenge",
    "MonthlyCharge",
    "RatePlan",
    "Season",
    "TieredUsageCharge",
    "TimeOfUseCharge",
    "TimeOfUsePeriod",
    "TimeWindow",
    "UsageRead",
    "UsageTier",
    "UsageUnit",
    "create_cookie_jar",
    "get_available_rate_plans",
    "get_rate_plan",
]
